services:
  db:
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    ports: [] # do not expose backend publicly in prod; proxied via frontend
    environment:
      - TZ=Europe/Moscow
      - DATABASE_URL=postgresql://postgres:password@db:5432/bizcard_crm
      - APP_VERSION=v1.5
      - APP_COMMIT=
      - APP_MESSAGE=VK Cloud deploy, proxy, relative URLs, DB init retry
    volumes:
      - ./uploads:/app/uploads

  frontend:
    ports:
      - '80:80'

volumes:
  pgdata:
