services:
  db:
    image: postgres:15
    container_name: bizcard-db
    environment:
      POSTGRES_DB: bizcard_crm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: bizcard-redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build: ./backend
    container_name: bizcard-backend
    environment:
      - TZ=Europe/Berlin
      - APP_VERSION=v2.4
      - APP_MESSAGE=Automation & UX Enhancements
      - DATABASE_URL=postgresql://postgres:password@db:5432/bizcard_crm
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - PARSIO_API_URL=${PARSIO_API_URL:-}
      - PARSIO_API_KEY=${PARSIO_API_KEY:-}
      - PARSIO_AUTH_HEADER_NAME=${PARSIO_AUTH_HEADER_NAME:-Authorization}
      - PARSIO_AUTH_HEADER_VALUE=${PARSIO_AUTH_HEADER_VALUE:-Bearer {key}}
      - PARSIO_TIMEOUT=${PARSIO_TIMEOUT:-30}
      - WHATSAPP_API_URL=${WHATSAPP_API_URL:-https://graph.facebook.com/v18.0}
      - WHATSAPP_PHONE_ID=${WHATSAPP_PHONE_ID:-}
      - WHATSAPP_ACCESS_TOKEN=${WHATSAPP_ACCESS_TOKEN:-}
      - WHATSAPP_VERIFY_TOKEN=${WHATSAPP_VERIFY_TOKEN:-ibbase_verify_token_2024}
    volumes:
      - ./backend/app:/app/app
      - ./uploads:/app/uploads
      - ./backups:/home/ubuntu/fastapi-bizcard-crm-ready/backups
      - ./scripts:/home/ubuntu/fastapi-bizcard-crm-ready/scripts:ro
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis

  celery-worker:
    build: ./backend
    container_name: bizcard-celery-worker
    command: celery -A app.celery_app worker --loglevel=info --concurrency=2
    environment:
      - TZ=Europe/Berlin
      - DATABASE_URL=postgresql://postgres:password@db:5432/bizcard_crm
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - PARSIO_API_URL=${PARSIO_API_URL:-}
      - PARSIO_API_KEY=${PARSIO_API_KEY:-}
      - PARSIO_AUTH_HEADER_NAME=${PARSIO_AUTH_HEADER_NAME:-Authorization}
      - PARSIO_AUTH_HEADER_VALUE=${PARSIO_AUTH_HEADER_VALUE:-Bearer {key}}
      - PARSIO_TIMEOUT=${PARSIO_TIMEOUT:-30}
      - WHATSAPP_API_URL=${WHATSAPP_API_URL:-https://graph.facebook.com/v18.0}
      - WHATSAPP_PHONE_ID=${WHATSAPP_PHONE_ID:-}
      - WHATSAPP_ACCESS_TOKEN=${WHATSAPP_ACCESS_TOKEN:-}
      - WHATSAPP_VERIFY_TOKEN=${WHATSAPP_VERIFY_TOKEN:-ibbase_verify_token_2024}
    volumes:
      - ./backend/app:/app/app
      - ./uploads:/app/uploads
    depends_on:
      - db
      - redis
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: bizcard-frontend
    depends_on:
      - backend
    ports:
      - '3000:80'
      - '8443:8443'
    volumes:
      - /etc/nginx/certs:/etc/nginx/certs:ro

volumes:
  postgres_data:
  redis_data:
