services:
  db:
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    ports: [] # do not expose backend publicly in prod; proxied via frontend
    environment:
      - TZ=Europe/Moscow
      - DATABASE_URL=postgresql://postgres:password@db:5432/bizcard_crm
      - APP_VERSION=v1.7
      - APP_COMMIT=
      - APP_MESSAGE=Modern UI, OCR provider management, enhanced web settings
    volumes:
      - ./uploads:/app/uploads

  frontend:
    ports:
      - '80:80'
      - '8443:8443'
    volumes:
      - /etc/nginx/certs:/etc/nginx/certs:ro

volumes:
  pgdata:
