# Full Monitoring Stack - Production Configuration
# All ports bound to localhost only (127.0.0.1) except Grafana (через Nginx)

services:
  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: bizcard-prometheus
    restart: unless-stopped
    ports:
      - "127.0.0.1:9090:9090"  # Только localhost!
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=15d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - monitoring

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: bizcard-grafana
    restart: unless-stopped
    ports:
      - "127.0.0.1:3001:3000"  # Только localhost! (доступ через Nginx)
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_SERVER_ROOT_URL=https://monitoring.ibbase.ru
      - GF_SERVER_DOMAIN=monitoring.ibbase.ru
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_ANALYTICS_CHECK_FOR_UPDATES=false
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - monitoring

  # cAdvisor
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: bizcard-cadvisor
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - "127.0.0.1:8080:8080"  # Только localhost!
    networks:
      - monitoring
    command:
      - '--housekeeping_interval=10s'
      - '--docker_only=true'
      - '--disable_metrics=percpu,sched,tcp,udp,disk,diskIO,accelerator,hugetlb,referenced_memory,cpu_topology,resctrl'

  # Node Exporter
  node-exporter:
    image: prom/node-exporter:latest
    container_name: bizcard-node-exporter
    restart: unless-stopped
    ports:
      - "127.0.0.1:9100:9100"  # Только localhost!
    command:
      - '--path.rootfs=/host'
    volumes:
      - /:/host:ro,rslave
    networks:
      - monitoring

  # Redis Exporter
  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: bizcard-redis-exporter
    restart: unless-stopped
    ports:
      - "127.0.0.1:9121:9121"  # Только localhost!
    environment:
      - REDIS_ADDR=redis:6379
    networks:
      - monitoring
      - fastapi-bizcard-crm-ready_default

  # PostgreSQL Exporter
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: bizcard-postgres-exporter
    restart: unless-stopped
    ports:
      - "127.0.0.1:9187:9187"  # Только localhost!
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:${DB_PASSWORD:-password}@db:5432/bizcard_crm?sslmode=disable
    networks:
      - monitoring
      - fastapi-bizcard-crm-ready_default

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  monitoring:
    external: true
  fastapi-bizcard-crm-ready_default:
    external: true

