# ClamAV Antivirus Service (Optional)
# Add to main docker-compose.yml if needed

version: '3.8'

services:
  clamav:
    image: clamav/clamav:latest
    container_name: bizcard-clamav
    restart: unless-stopped
    volumes:
      - clamav_data:/var/lib/clamav
    ports:
      - "127.0.0.1:3310:3310"
    environment:
      - CLAMAV_NO_FRESHCLAM=false
    healthcheck:
      test: ["CMD", "clamdscan", "--ping"]
      interval: 60s
      timeout: 10s
      retries: 3
    networks:
      - default

volumes:
  clamav_data:
    driver: local

networks:
  default:
    external: true
    name: fastapi-bizcard-crm-ready_default

