services:
  db:
    image: postgres:15
    container_name: bizcard-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-bizcard_crm}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD must be set in .env file}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"

  redis:
    image: redis:7-alpine
    container_name: bizcard-redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "127.0.0.1:6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build: ./backend
    container_name: bizcard-backend
    environment:
      - TZ=Europe/Berlin
      - APP_VERSION=v2.14
      - APP_MESSAGE=Modular Architecture Completion
      - SERVER_HOST=ibbase.ru
      - DOMAIN=ibbase.ru
      - USE_HTTPS=true
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB:-bizcard_crm}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB:-bizcard_crm}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - PARSIO_API_URL=${PARSIO_API_URL:-}
      - PARSIO_API_KEY=${PARSIO_API_KEY:-}
      - PARSIO_AUTH_HEADER_NAME=${PARSIO_AUTH_HEADER_NAME:-Authorization}
      - PARSIO_AUTH_HEADER_VALUE=${PARSIO_AUTH_HEADER_VALUE:-Bearer {key}}
      - PARSIO_TIMEOUT=${PARSIO_TIMEOUT:-30}
      - WHATSAPP_API_URL=${WHATSAPP_API_URL:-https://graph.facebook.com/v18.0}
      - WHATSAPP_PHONE_ID=${WHATSAPP_PHONE_ID:-}
      - WHATSAPP_ACCESS_TOKEN=${WHATSAPP_ACCESS_TOKEN:-}
      - WHATSAPP_VERIFY_TOKEN=${WHATSAPP_VERIFY_TOKEN:?WHATSAPP_VERIFY_TOKEN must be set in .env file}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT:-minio:9000}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-admin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minio123456}
      - MINIO_SECURE=${MINIO_SECURE:-false}
    volumes:
      - ./backend/app:/app/app
      - ./uploads:/app/uploads
      - ./backups:/app/backups
      - ./training_data:/app/training_data
      - ./models:/app/models
      - ./scripts:/home/ubuntu/fastapi-bizcard-crm-ready/scripts:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - .:/home/ubuntu/fastapi-bizcard-crm-ready:ro
    ports:
      - '127.0.0.1:8000:8000'
    depends_on:
      - db
      - redis
    deploy:
      resources:
        limits:
          memory: 1536M
        reservations:
          memory: 768M
    mem_swappiness: 60

  celery-worker:
    build: ./backend
    container_name: bizcard-celery-worker
    command: python -m celery -A app.celery_app worker --loglevel=info --concurrency=1
    environment:
      - TZ=Europe/Berlin
      - C_FORCE_ROOT=true
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB:-bizcard_crm}
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - PARSIO_API_URL=${PARSIO_API_URL:-}
      - PARSIO_API_KEY=${PARSIO_API_KEY:-}
      - PARSIO_AUTH_HEADER_NAME=${PARSIO_AUTH_HEADER_NAME:-Authorization}
      - PARSIO_AUTH_HEADER_VALUE=${PARSIO_AUTH_HEADER_VALUE:-Bearer {key}}
      - PARSIO_TIMEOUT=${PARSIO_TIMEOUT:-30}
      - WHATSAPP_API_URL=${WHATSAPP_API_URL:-https://graph.facebook.com/v18.0}
      - WHATSAPP_PHONE_ID=${WHATSAPP_PHONE_ID:-}
      - WHATSAPP_ACCESS_TOKEN=${WHATSAPP_ACCESS_TOKEN:-}
      - WHATSAPP_VERIFY_TOKEN=${WHATSAPP_VERIFY_TOKEN:?WHATSAPP_VERIFY_TOKEN must be set in .env file}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT:-minio:9000}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-admin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minio123456}
      - MINIO_SECURE=${MINIO_SECURE:-false}
    volumes:
      - ./backend/app:/app/app
      - ./uploads:/app/uploads
      - ./training_data:/app/training_data
      - ./models:/app/models
    depends_on:
      - db
      - redis
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    mem_swappiness: 60

  frontend:
    build: ./frontend
    container_name: bizcard-frontend
    depends_on:
      - backend
    ports:
      - '127.0.0.1:3000:80'

  label-studio:
    image: heartexlabs/label-studio:latest
    container_name: bizcard-label-studio
    environment:
      - LABEL_STUDIO_HOST=https://ibbase.ru
      - LABEL_STUDIO_BASE_URL=/label-studio
      - LABEL_STUDIO_USERNAME=${LABEL_STUDIO_USERNAME:-admin@ibbase.ru}
      - LABEL_STUDIO_PASSWORD=${LABEL_STUDIO_PASSWORD:?LABEL_STUDIO_PASSWORD must be set in .env file}
      - LABEL_STUDIO_USER_TOKEN=${LABEL_STUDIO_TOKEN:-}
      - LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
      - LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/label-studio/files
    volumes:
      - label_studio_data:/label-studio/data
      - ./uploads:/label-studio/files:ro  # Read-only access to business card images
    ports:
      - '127.0.0.1:8081:8080'
    restart: unless-stopped
    command: label-studio start --init

  minio:
    image: minio/minio:latest
    container_name: bizcard-minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-admin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minio123456}
      # Let MinIO Console handle paths internally
      MINIO_BROWSER_REDIRECT: "on"
    volumes:
      - minio_data:/data
    ports:
      - '127.0.0.1:9000:9000'  # API
      - '127.0.0.1:9001:9001'  # Console
    command: server /data --console-address ":9001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  postgres_data:
  redis_data:
  label_studio_data:
  minio_data:
