# Monitoring Stack for BizCard CRM
# Usage: docker compose -f docker-compose.yml -f docker-compose.monitoring.yml up -d

services:
  # Prometheus - Metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: bizcard-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./monitoring/prometheus/alerts.yml:/etc/prometheus/alerts.yml:ro
      - prometheus_data:/prometheus
    ports:
      - '9090:9090'
    networks:
      - default
    restart: unless-stopped
    depends_on:
      - backend

  # Grafana - Visualization and dashboards
  grafana:
    image: grafana/grafana:latest
    container_name: bizcard-grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources:ro
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=http://localhost:3001
      - GF_INSTALL_PLUGINS=
    ports:
      - '3001:3000'
    networks:
      - default
    restart: unless-stopped
    depends_on:
      - prometheus

  # Node Exporter - System metrics (CPU, RAM, Disk)
  node-exporter:
    image: prom/node-exporter:latest
    container_name: bizcard-node-exporter
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    ports:
      - '9100:9100'
    networks:
      - default
    restart: unless-stopped

  # PostgreSQL Exporter - Database metrics
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: bizcard-postgres-exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:password@db:5432/bizcard_crm?sslmode=disable
    ports:
      - '9187:9187'
    networks:
      - default
    restart: unless-stopped
    depends_on:
      - db

  # cAdvisor - Container metrics
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: bizcard-cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - '8080:8080'
    networks:
      - default
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/kmsg

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

