name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install backend deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      - name: Quick import checks
        run: |
          python - << 'PY'
          import fastapi, sqlalchemy, pandas
          print('Imports OK')
          PY

  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Cache npm (frontend)
        uses: actions/cache@v4
        with:
          path: frontend/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install and build
        working-directory: frontend
        run: |
          mkdir -p .npm
          if [ -f package-lock.json ]; then npm ci --cache .npm; else npm install --cache .npm; fi
          npm run build
